# Numpy Basics <hr style="border:2.px solid #Ff0cb"></hr>

Data Analyst: Charles Ian Gabriel M. Guevarra <br>
Department: Electrical Engineering

In [47]:
# imports and packages  
import numpy as np
from scipy import stats

# 1D Array

In [48]:
array_1 = np.array([1, 2, 3])
array_1

array([1, 2, 3])

# 2D Array

In [60]:
my_array = np.array([
    [1,2,3],
    [4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
my_array = my_array.T

In [62]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [63]:
np.sum(my_array)

np.int64(21)

In [64]:
# add by row
np.sum(my_array,axis=0)

array([ 6, 15])

In [65]:
# by column
np.sum(my_array,axis=1)

array([5, 7, 9])

# Measures of Central Tendency

In [52]:
fruits = np.array([120,60,85,150,200])
fruits 

array([120,  60,  85, 150, 200])

In [53]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [54]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [55]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguear vs Panther

## Jaguar

In [69]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [70]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [74]:
median_jag = np.median(jaguar)
median_jag

np.float64(9.8)

In [76]:
mode_jag = stats.mode(jaguar)
mode_jag

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [77]:
max_jag = np.max(jaguar)
min_jag = np.min(jaguar)

range_jag = max_jag - min_jag
range_jag


np.float64(8.0)

In [80]:
# Q1
q1_jag = np.percentile(jaguar,25)
q1_jag

np.float64(9.4)

In [81]:
# Q2 (median)
q2_jag = np.percentile(jaguar,50)
q2_jag

np.float64(9.8)

In [82]:
# Q3
q3_jag = np.percentile(jaguar,75)
q3_jag

np.float64(10.45)

In [83]:
# IQR
iqr_jag = q3_jag - q1_jag
iqr_jag

np.float64(1.049999999999999)

In [85]:
# sample variance
var_jag = np.var(jaguar,ddof=1)
var_jag

np.float64(4.86)

In [86]:
# sample standard deviation
std_jag = np.std(jaguar,ddof=1)
std_jag

np.float64(2.2045407685048604)

## Panther

In [58]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [59]:
panther_mean = np.mean(panther)
panther_mean

np.float64(10.75)

In [87]:
panther_median = np.median(panther)
panther_median

np.float64(9.55)

In [88]:
median_pan = np.median(panther)
median_pan

np.float64(9.55)

In [90]:
mode_pan = stats.mode(panther)
mode_pan

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [94]:
max_pan = np.max(panther)
min_pan = np.min(panther)

range_pan = max_pan - min_pan
range_pan


np.float64(10.9)

In [95]:
# Q1
q1_pan = np.percentile(panther,25)
q1_pan

np.float64(9.125)

In [97]:
# Q2 (median)
q2_pan = np.percentile(panther,50)
q2_pan

np.float64(9.55)

In [98]:
# Q3
q3_pan = np.percentile(panther,75)
q3_pan

np.float64(10.625)

In [99]:
# IQR
iqr_pan = q3_pan - q1_pan
iqr_pan

np.float64(1.5)